import {
  FaServer,
  FaDatabase,
  FaCloud,
  FaTerminal,
  FaShieldHalved,
} from "react-icons/fa6";
import { PiMonitorFill } from "react-icons/pi";

export const SKILLS_DATA = [
  {
    id: "backend",
    title: "Backend & Architecture",
    isPrimary: true,
    icon: FaServer,
    description: "High-performance server-side services, domain modeling, and robust API architectures.",
    skills: [
      "ASP.NET Core Web API",
      "C#",
      "RESTful APIs",
      "Clean Architecture",
      "JWT & Authorization",
      "Entity Framework Core",
      "Dapper",
      "API Integration",
    ],
  },
  {
    id: "databases",
    title: "Databases & Performance",
    icon: FaDatabase,
    description: "Relational data design, stored procedures, indexing, and query execution plan tuning.",
    skills: [
      "Microsoft SQL Server",
      "T-SQL & Stored Procedures",
      "Index Optimization",
      "Query Performance Tuning",
      "Execution Plan Analysis",
      "MongoDB",
      "Oracle DB",
    ],
  },
  {
    id: "cloud",
    title: "Cloud & Enterprise Platforms",
    icon: FaCloud,
    description: "Cloud-native services, Azure deployments, and enterprise intranet automation solutions.",
    skills: [
      "Microsoft Azure",
      "Azure App Services",
      "Azure Functions",
      "Azure SQL Database",
      "SharePoint Online",
      "SharePoint Framework (SPFx)",
      "Cloud Deployment",
    ],
  },
  {
    id: "frontend",
    title: "Frontend & UI Engineering",
    icon: PiMonitorFill,
    description: "Reactive web interfaces with responsive layouts, fluid animations, and component architecture.",
    skills: [
      "React.js",
      "JavaScript (ES6+)",
      "HTML5 & Semantic Web",
      "Modern CSS & Flexbox/Grid",
      "Responsive UI/UX",
      "Framer Motion",
      "State Management",
    ],
  },
  {
    id: "tools",
    title: "DevOps & Engineering Tools",
    icon: FaTerminal,
    description: "Version control, API telemetry, automated pipelines, testing, and developer tooling.",
    skills: [
      "Git & GitHub",
      "Postman & API Telemetry",
      "CI/CD Automation",
      "Visual Studio",
      "VS Code",
      "Swagger / OpenAPI",
      "Docker Basics",
    ],
  },
  {
    id: "security",
    title: "Security & Standards",
    icon: FaShieldHalved,
    description: "Defensive engineering, claims-based access controls, sanitization, and data protection.",
    skills: [
      "Role-Based Access Control (RBAC)",
      "OAuth & JWT Best Practices",
      "Input Validation & Sanitization",
      "SQL Injection Prevention",
      "CORS Configuration",
      "Secure API Design",
    ],
  },
];
