export const EXPERIENCE_LIST = [
  {
    id: 1,
    title: "Junior Software Developer",
    company: "QuiperSoft Technologies Pvt Ltd.",
    location: "Chennai, India",
    duration: "2024 – 2025",
    type: "Full-Time",
    responsibilities: [
      "Developed and maintained RESTful APIs using ASP.NET Core and C# for enterprise applications.",
      "Implemented JWT Authentication and role-based authorization to secure API endpoints.",
      "Designed and optimized SQL Server database queries, stored procedures, and Entity Framework Core operations.",
      "Collaborated with frontend developers to integrate APIs with React.js applications.",
      "Participated in debugging, testing, and resolving production issues to improve application stability.",
    ],
    techStack: [
      "ASP.NET Core",
      "C#",
      "RESTful APIs",
      "JWT Authentication",
      "SQL Server",
      "Entity Framework Core",
      "React.js",
    ],
  },
  {
    id: 2,
    title: "Junior Software Developer",
    company: "ExcelGoodies Consulting, Inc.",
    location: "Chennai, India",
    duration: "2023 – 2024",
    type: "Full-Time",
    responsibilities: [
      "Designed and developed scalable backend services using ASP.NET Core Web API following Clean Architecture principles.",
      "Built secure REST APIs with JWT Authentication, authorization, and robust exception handling.",
      "Developed Azure-based backend workflows using the Azure SDK for virtual machine provisioning and management.",
      "Optimized SQL Server queries and Entity Framework Core operations to improve application performance.",
      "Collaborated with cross-functional teams during feature development, code reviews, and deployment activities.",
    ],
    techStack: [
      "ASP.NET Core Web API",
      "C#",
      "Clean Architecture",
      "Azure SDK",
      "SQL Server",
      "Entity Framework Core",
      "REST APIs",
    ],
  },
];
